/*https://www.hackerrank.com/challenges/interviews/problem*/

SELECT CON.CONTEST_ID, CON.HACKER_ID, CON.NAME, SUM(SS.TOTAL_SUBMISSIONS), SUM(SS.TOTAL_ACCEPTED_SUBMISSIONS), SUM(VS.TOTAL_VIEWS), SUM(VS.TOTAL_UNIQUE_VIEWS) FROM CONTESTS CON
JOIN COLLEGES COLL
ON CON.CONTEST_ID = COLL.CONTEST_ID
JOIN CHALLENGES CHAL
ON COLL.COLLEGE_ID = CHAL.COLLEGE_ID
LEFT JOIN (SELECT CHALLENGE_ID, SUM(TOTAL_VIEWS) AS TOTAL_VIEWS, SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS FROM VIEW_STATS GROUP BY CHALLENGE_ID) VS
ON CHAL.CHALLENGE_ID = VS.CHALLENGE_ID
LEFT JOIN (SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS FROM SUBMISSION_STATS GROUP BY CHALLENGE_ID) SS
ON CHAL.CHALLENGE_ID = SS.CHALLENGE_ID
GROUP BY CON.CONTEST_ID, CON.HACKER_ID, CON.NAME
HAVING SUM(VS.TOTAL_VIEWS)+ SUM(VS.TOTAL_UNIQUE_VIEWS)+ SUM(SS.TOTAL_SUBMISSIONS)+ SUM(SS.TOTAL_ACCEPTED_SUBMISSIONS) > 0
ORDER BY CON.CONTEST_ID;
