/*https://www.hackerrank.com/challenges/full-score/problem*/


SELECT S.HACKER_ID,H.NAME FROM
SUBMISSIONS S
JOIN CHALLENGES C
ON S.CHALLENGE_ID = C.CHALLENGE_ID
JOIN DIFFICULTY D
ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
JOIN HACKERS H
ON H.HACKER_ID = S.HACKER_ID
WHERE S.SCORE = D.SCORE
GROUP BY S.HACKER_ID,H.NAME
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC, S.HACKER_ID ASC;
