/*https://www.hackerrank.com/challenges/contest-leaderboard/problem*/

SELECT H.HACKER_ID, H.NAME, SUM(BEST_SCORE) AS HACKER_SCORE
FROM HACKERS H
JOIN
(SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS BEST_SCORE
FROM SUBMISSIONS
GROUP BY HACKER_ID, CHALLENGE_ID) S
ON H.HACKER_ID = S.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(BEST_SCORE) > 0
ORDER BY 3 DESC, 1;
