/*https://www.hackerrank.com/challenges/harry-potter-and-wands/problem*/

SELECT W_1.ID, W_2.AGE, W_2.COINS_NEEDED, W_2.POWER
FROM WANDS W_1
JOIN
(SELECT W.CODE, W_P.AGE, MIN(W.COINS_NEEDED) COINS_NEEDED, W.POWER
FROM WANDS W JOIN WANDS_PROPERTY W_P
ON W.CODE = W_P.CODE
WHERE W_P.IS_EVIL = 0
GROUP BY W.CODE, W_P.AGE, W.POWER) W_2
ON W_1.COINS_NEEDED = W_2.COINS_NEEDED
AND W_1.CODE = W_2.CODE
ORDER BY W_2.POWER DESC, W_2.AGE DESC;
