/*https://www.hackerrank.com/challenges/the-company/problem*/

SELECT COM.COMPANY_CODE, COM.FOUNDER, COUNT(DISTINCT LM.LEAD_MANAGER_CODE), COUNT(DISTINCT SM.SENIOR_MANAGER_CODE), COUNT(DISTINCT M.MANAGER_CODE), COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY COM
JOIN LEAD_MANAGER LM
ON LM.COMPANY_CODE = COM.COMPANY_CODE
JOIN SENIOR_MANAGER SM
ON SM.COMPANY_CODE = LM.COMPANY_CODE
AND SM.LEAD_MANAGER_CODE = LM.LEAD_MANAGER_CODE
JOIN MANAGER M
ON M.COMPANY_CODE = SM.COMPANY_CODE
AND M.LEAD_MANAGER_CODE = SM.LEAD_MANAGER_CODE
AND M.SENIOR_MANAGER_CODE = SM.SENIOR_MANAGER_CODE
JOIN EMPLOYEE E
ON E.COMPANY_CODE = M.COMPANY_CODE
AND E.LEAD_MANAGER_CODE = M.LEAD_MANAGER_CODE
AND E.SENIOR_MANAGER_CODE = M.SENIOR_MANAGER_CODE
AND E.MANAGER_CODE = M.MANAGER_CODE
GROUP BY COM.COMPANY_CODE, COM.FOUNDER
ORDER BY 1,2;
