/*https://www.hackerrank.com/challenges/placements/problem*/

SELECT ST1.NAME FROM STUDENTS ST1
JOIN FRIENDS F ON ST1.ID = F.ID
JOIN PACKAGES P1 ON ST1.ID = P1.ID
JOIN PACKAGES P2 ON F.FRIEND_ID = P2.ID
WHERE P1.SALARY < P2.SALARY
ORDER BY P2.SALARY;
