/*https://www.hackerrank.com/challenges/print-prime-numbers/problem*/

WITH NUMEROS(NUMERO) AS (
    SELECT 2 AS NUMERO FROM DUAL
    UNION ALL
    SELECT NUMERO+1 FROM NUMEROS WHERE NUMERO < 1000
) SELECT LISTAGG(TO_CHAR(NUM.NUMERO), '&') WITHIN GROUP (ORDER BY NUM.NUMERO)
FROM NUMEROS NUM
WHERE NOT EXISTS (
    SELECT NUMERO FROM NUMEROS N2
    WHERE N2.NUMERO <= SQRT(NUM.NUMERO)
    AND MOD(NUM.NUMERO, N2.NUMERO) = 0
)
;
