/*https://www.hackerrank.com/challenges/symmetric-pairs/problem*/

SELECT DISTINCT X,Y FROM FUNCTIONS F WHERE EXISTS
(SELECT LEAST(F2.X, F2.Y), GREATEST(F2.X,F2.Y), COUNT(*) FROM FUNCTIONS F2
 WHERE LEAST(F2.X, F2.Y) = F.X AND GREATEST(F2.X,F2.Y) = F.Y
GROUP BY LEAST(F2.X, F2.Y), GREATEST(F2.X,F2.Y)
HAVING COUNT(*) > 1)
ORDER BY 1 ASC;

-----------

SELECT DISTINCT X,Y FROM FUNCTIONS F WHERE (X,Y) IN
(SELECT LEAST(F2.X, F2.Y), GREATEST(F2.X,F2.Y) FROM FUNCTIONS F2
GROUP BY LEAST(F2.X, F2.Y), GREATEST(F2.X,F2.Y)
HAVING COUNT(*) > 1)
ORDER BY 1 ASC;
