/*https://www.codewars.com/kata/5811527d9d278b242f000006*/

CREATE VIEW MEMBERS_APPROVED_FOR_VOUCHER
AS SELECT M.ID AS ID, M.NAME AS NAME, M.EMAIL AS EMAIL, SUM(P.PRICE) AS TOTAL_SPENDING
FROM SALES S
JOIN PRODUCTS P ON S.PRODUCT_ID = P.ID
JOIN (SELECT D1.ID AS ID, SUM(P1.PRICE) AS TOTAL_ORDERED
  FROM SALES S1
  JOIN DEPARTMENTS D1
  ON D1.ID = S1.DEPARTMENT_ID
  JOIN PRODUCTS P1
  ON S1.PRODUCT_ID = P1.ID
  GROUP BY D1.ID
  HAVING SUM(P1.PRICE) > 10000)
  GOOD_DEP
ON S.DEPARTMENT_ID = GOOD_DEP.ID
JOIN MEMBERS M
ON M.ID = S.MEMBER_ID
GROUP BY M.ID, M.NAME, M.EMAIL
HAVING SUM(P.PRICE) > 1000
ORDER BY 1 ASC;

SELECT * FROM MEMBERS_APPROVED_FOR_VOUCHER;
