/*https://www.codewars.com/kata/5811597e9d278beb04000038*/

SELECT E.CREATED_AT::DATE AS DAY, E.DESCRIPTION, COUNT(1)
FROM EVENTS E
WHERE lower(E.NAME) LIKE '%trained%'
GROUP BY E.CREATED_AT::DATE, E.DESCRIPTION
ORDER BY 1 ASC;
