/*https://www.codewars.com/kata/58113a64e10b53ec36000293*/

SELECT ID, NAME FROM DEPARTMENTS WHERE EXISTS
(SELECT ID, DEPARTMENT_ID FROM SALES
  WHERE DEPARTMENTS.ID = SALES.DEPARTMENT_ID AND SALES.PRICE > 98);
