/*https://www.codewars.com/kata/580d08b5c049aef8f900007c*/

SELECT C.CUSTOMER_ID, C.EMAIL, COUNT(P.PAYMENT_ID) AS PAYMENTS_COUNT, SUM(CAST(P.AMOUNT AS FLOAT)) AS TOTAL_AMOUNT
FROM CUSTOMER C
JOIN PAYMENT P
ON C.CUSTOMER_ID = P.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.EMAIL
ORDER BY TOTAL_AMOUNT DESC
LIMIT 10;
