/*https://www.codewars.com/kata/5818bde9559ff58bd90004a2*/

SELECT A1.FIRST_NAME || ' ' || A1.LAST_NAME AS FIRST_ACTOR, A2.FIRST_NAME || ' ' || A2.LAST_NAME AS SECOND_ACTOR, FILM.TITLE AS TITLE
FROM FILM_ACTOR FA3
JOIN FILM_ACTOR FA4
ON FA3.FILM_ID = FA4.FILM_ID
INNER JOIN
(SELECT FA1.ACTOR_ID AS FIRST_ACTOR, FA2.ACTOR_ID AS SECOND_ACTOR, COUNT(1) AS FILMS_TOGETHER
FROM FILM_ACTOR FA1
JOIN FILM_ACTOR FA2
ON FA1.FILM_ID = FA2.FILM_ID
WHERE FA1.ACTOR_ID < FA2.ACTOR_ID
GROUP BY FA1.ACTOR_ID, FA2.ACTOR_ID
ORDER BY 3 DESC
LIMIT 1) FINAL_ACTORS
ON FINAL_ACTORS.FIRST_ACTOR = FA3.ACTOR_ID AND FINAL_ACTORS.SECOND_ACTOR = FA4.ACTOR_ID
JOIN ACTOR A1
ON A1.ACTOR_ID = FA3.ACTOR_ID
JOIN ACTOR A2
ON A2.ACTOR_ID = FA4.ACTOR_ID
JOIN FILM
ON FA3.FILM_ID = FILM.FILM_ID
ORDER BY 3 ASC;
