/*https://www.codewars.com/kata/5977b6641e250a661a0000f0*/

SELECT V.ENTRY_TIME AS WHEN_HAPPENED, COUNT(*) AS VISITS_COUNT
FROM VISITS V
LEFT JOIN VISITS V2
ON V.ENTRY_TIME >= V2.ENTRY_TIME AND V.ENTRY_TIME < V2.EXIT_TIME
GROUP BY V.ID, V.ENTRY_TIME
ORDER BY 2 DESC,1 ASC
LIMIT 1;
