/*https://www.codewars.com/kata/5812a2a2492760dfca000450*/

WITH RECURSIVE subordinates (LEVEL) AS (
SELECT 1 AS EMPLOYEE_LEVELS,  E1.ID AS ID, E1.FIRST_NAME AS FIRST_NAME, E1.LAST_NAME AS LAST_NAME, E3.ID AS MANAGER_ID
  FROM EMPLOYEES E1
  LEFT JOIN EMPLOYEES E3
  ON E1.MANAGER_ID = E3.ID
  WHERE E3.ID IS NULL
UNION
SELECT
    LEVEL+1, E2.ID, E2.FIRST_NAME, E2.LAST_NAME, S.ID
      FROM
         EMPLOYEES E2
      INNER JOIN subordinates s ON s.ID = e2.MANAGER_ID
)
SELECT * FROM subordinates ORDER BY 1,2,3;
